[package]
name = "fruitsys_open_tables_summarizer"
version = "0.1.2"
edition = "2021"

[dependencies]
dotenv = "0.15"
reqwest = { version = "0.12", features = ["blocking", "cookies"] }
scraper = "0.23"
